### ISSUE TITLE
Consider checking in `Cargo.lock`?

### ISSUE THREAD

**Issue by erictapen** [esp-rs/espflash#107]
Hey, thanks for writing this project.

Adding the lockfile to the repository would make it much easier to package it in distributions like Nixpkgs. It is also the recommended action for [crates that are mainly applications for endusers](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock).

**Comment by jessebraham** [comment]
Thanks for this. We actually had an issue with the release of `clap==3.0.0-rc.1` recently which caused issues and made me think the same thing.

Given that we have two applications and one library in this repository, I think it makes sense to go with the majority and include the `Cargo.lock` file.
