### ISSUE TITLE
Cannot flash OTA partition

### ISSUE THREAD

**Issue by bugadani** [esp-rs/espflash#111]
I have a project where I have 2 ota partitions and no factory partition. espflash.exe fails flashing an image with the error `  ╰─▶ No factory app partition was found`.

**Comment by jessebraham** [comment]
Thanks for opening this.

I went in with the assumption that the `factory` partition was required, which does not appear to be the case. Should be a fairly simple fix I think, I'll try to take a look at it this week.

**Comment by bugadani** [comment]
I can also try and take a look, should you be out of time :)

**Comment by jessebraham** [comment]
That would be great! :)
