### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/espflash#120]
Seems CI is broken on in pre build step: https://github.com/esp-rs/espflash/blob/92a266d92e6e85f04114e555e0b7951544386a65/.github/workflows/rust.yml#L10

https://github.com/esp-rs/espflash/runs/4833785313?check_suite_focus=true

**Comment by jessebraham** [comment]
Thanks for pointing this out. The error reported was:

```text
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_245.4-4ubuntu3.14_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I did some searching and it seems we're hardly the only people experiencing this issue. Fortunately, I was able to fix this by switching from the Azure mirror to the official Ubuntu archives. PR incoming.
