### ISSUE TITLE
Allow customization of firmware image headers

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/espflash#140]
Currently every firmware image we create with `from_elf` has hard coded flash attributes

https://github.com/esp-rs/espflash/blob/eeb0e8f95d184209cc42be9c4fec15c7172729fc/espflash/src/elf.rs#L49-L57

We should add CLI options to configure these, for the cases where the flash size of a chip may be different (see: https://github.com/esp-rs/esp-idf-template/issues/15)

**Comment by jessebraham** [comment]
Should hopefully have a PR ready for this tomorrow. I managed to implement most of this today, just need to clean up some rough edges and do a bunch of testing still.
