### ISSUE TITLE
Argument parsing for multiple features is broken

### ISSUE THREAD

**Issue by svenstaro** [esp-rs/espflash#161]
The arguments are currently parsed incorrectly when multiple comma-separated features are provided such as in `--features hello,hola`. It gets put into the cargo command like this: `--features hello hola`.

**Comment by jessebraham** [comment]
I believe that is still valid, no? From running `cargo build --help` it displays:

```
--features <FEATURES>       Space or comma separated list of features to activate
```

Which indicates that spaces or commas are accepted.

**Comment by svenstaro** [comment]
But space separated the way they are currently produced will end up as non-feature arguments.  You can try it yourself and it will pop out as incorrect if you provide something like --features a,b.

**Comment by jessebraham** [comment]
Ahh okay, thanks for clarifying.
