### ISSUE TITLE
Expose partition table csv->bin and bin->csv parsers as subcommand

### ISSUE THREAD

**Issue by svenstaro** [esp-rs/espflash#163]
This tool is quite handy in that it does the partition table juggling for you. However, it only does it as part of its internal process. What do you think about exposing that stuff explicitly as a sub-command so that we may use in in place of [the esp-idf way](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html#generating-binary-partition-table)?

**Comment by jessebraham** [comment]
I think it would make sense to include this! I'm not sure when I will be able to get to it, though.
