### ISSUE TITLE
Add image info subcommand

### ISSUE THREAD

**Issue by svenstaro** [esp-rs/espflash#165]
It would be cool to have a subcommand to pretty print (with optional machine-readable output) the layout of the image (according to the partition table) as well as the actual app size within. This should be possible with either a connected board or a provided local image file.

**Comment by JurajSadel** [comment]
Hi @svenstaro, can you be more specific with the `layout of the image`, please? Do you mean `segments` in app binary or you are referring to something else?
Thanks!
