### ISSUE TITLE
Add support for building tests

### ISSUE THREAD

**Issue by svenstaro** [esp-rs/espflash#175]
I think it would be pretty cool if espflash could build/merge/flash test binaries.

**Comment by farbodpm** [comment]
there are some examples in probe-rs. have U checked it?

**Comment by svenstaro** [comment]
I checked it but do not know exactly which files you mean.

**Comment by dignifiedquire** [comment]
Any updates on this? would be great to use this to build test binaries to be executed in qemu and the end devices.

**Comment by SergioGasquez** [comment]
> Any updates on this? would be great to use this to build test binaries to be executed in qemu and the end devices.

Not really, for [`esp-hal` we are using `probe-rs` and `teleprobe` for HIL](https://github.com/esp-rs/esp-hal/issues/809#issuecomment-1802434224). Currently it only supports RISC-V (except for C2,[which should be soon supported](https://github.com/probe-rs/probe-rs/pull/1869). Xtensa support for probe-rs is also WIP. I would recommend going for this approach

**Comment by dignifiedquire** [comment]
> Xtensa support for probe-rs is also WIP. I would recommend going for this approach

is there a place to follow that progress?

**Comment by SergioGasquez** [comment]
> is there a place to follow that progress?

I dont think there is any tracking issue, feel free to join the [matrix channel](https://matrix.to/#/#esp-rs:matrix.org) where we post updates or you can asks for them

**Comment by bjoernQ** [comment]
There is a tracking issue for Xtensa in `probe-rs` now: https://github.com/probe-rs/probe-rs/issues/2001

**Comment by SergioGasquez** [comment]
I think we can close this issue as we won't be adding such feature to espflash. `probe-rs` can already flash tests into all the targets but ESP32 (see https://github.com/probe-rs/probe-rs/issues/2354), for an example see https://github.com/esp-rs/esp-hal/tree/main/hil-test
