### ISSUE TITLE
Add an option to cargo-espflash to flash file without having to build the project

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/espflash#198]
Maybe, if we have an argument pointing to an elf file, flash it instead of building the project and then flashing the resulting file.

**Comment by MabezDev** [comment]
This is what `espflash` does already! Easy to confuse with `cargo-espflash` which is the cargo wrapper that also builds the project. They are actually two different executables.

**Comment by SergioGasquez** [comment]
Sorry, I meant `cargo-espflash`. My point was to get this feature inside `cargo-espflash` so users that want to flash a file without building the project do not need to install `espflash` or rely on idf tool.

**Comment by tcbennun** [comment]
Agreed on this. It actually can cause a rebuild in some cases (e.g. performing a workspace build then using `cargo espflash` to flash one of the binary crates).

**Comment by MabezDev** [comment]
I believe this was closed via https://github.com/esp-rs/espflash/pull/205

**Comment by jessebraham** [comment]
This was closed erroneously, re-opening.

**Comment by jessebraham** [comment]
After thinking on this for awhile, I actually think it's not necessary. If the project is already built then normal execution is fine, the time added by `rustc` for an already built project is negligible.
