### ISSUE TITLE
"The parameter is incorrect" error when flashing from windows

### ISSUE THREAD

**Issue by mrhockeymonkey** [esp-rs/espflash#209]
Hi, 

I'm new to rust and embedded in general but I believe there is a regression in espflash 1.6.0 when running from windows. 

```plain
espflash COM3 .\target\xtensa-esp32-espidf\debug\test
Error: ←[31mespflash::serial_error←[0m

  ←[31mx←[0m Error while connecting to device
←[31m  |-> ←[0mIO error while using serial port: The parameter is incorrect. (os error 87)
←[31m  `-> ←[0mThe parameter is incorrect. (os error 87)
```

Running the same command on 1.5.1 is successful. My environment is Windows 10 (build 19044). Happy to provide any additional details if required.

**Comment by JurajSadel** [comment]
Hello @mrhockeymonkey! Sorry for the late reply, can you please try if the linked PR solves your issue?
