### ISSUE TITLE
support for esp32-pico-v3 devices

### ISSUE THREAD

**Issue by ryankurte** [esp-rs/espflash#215]
hi folks, thanks for all your work on such excellent tooling!

i'm trying to use this with (known working with `esptool.py`) `ESP32-PICO-V3` ICs, which results the error "Failed to connect to on-device flash" in `espflash::flash_connect`. afaik these are standard `ESP32`s (albeit with flash on chip instead of externally), so it should be possible to use these with `espflash` but may require some alternate configuration (though reports [here](https://github.com/esp-rs/espflash/issues/149#issuecomment-1105693726) suggest the `ESP32-PICO-D4` already works)?

output from `esptool.py`:
```
esptool.py --port /dev/ttyUSB0 flash_id
esptool.py v3.1
Serial port /dev/ttyUSB0
Connecting.....
Detecting chip type... ESP32
Chip is ESP32-PICO-V3-02 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, Embedded Flash, Embedded PSRAM, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 50:02:91:a5:80:48
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4017
Detected flash size: 8MB
Hard resetting via RTS pin...
```

relates to: https://github.com/esp-rs/esp-idf-template/issues/48

**Comment by ryankurte** [comment]
the docs suggest the configuration should be [the same](https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/advanced-options.html#custom-spi-pin-configuration) for the d4 and v3, is it that this isn't supported by the ROM stub loader?

**Comment by jessebraham** [comment]
Are you able to flash the device now that we're providing stubs, or is there still additional work required to close this?

**Comment by jessebraham** [comment]
Going to close this now, feel free to re-open if there's anything left to do.
