### ISSUE TITLE
Custom partition type

### ISSUE THREAD

**Issue by ollpu** [esp-rs/espflash#219]
I would like to add a custom a partition for more or less raw runtime storage (NVS API is not applicable). The docs at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html#creating-custom-tables recommend that application-defined partitions use the unreserved type values 0x40-0xFE.

Trying to flash a partition table like this:
```
# ESP-IDF Partition Table
# Name,   Type, SubType, Offset,  Size, Flags
nvs,data,nvs,0x9000,0x6000,
phy_init,data,phy,0xf000,0x1000,
factory,app,factory,0x10000,0x100000,
custom,0x40,0x00,0xf00000,0x100000,
```
gives an error
```
Error: espflash::partition_table::mallformed

  × Failed to parse partition table
  ├─▶ Malformed partition table
  ├─▶ CSV deserialize error: record 3 (line: 6, byte: 171): unknown variant `0x40`, expected `app` or `data`
  ╰─▶ unknown variant `0x40`, expected `app` or `data`
   ╭─[5:1]
 5 │ factory,app,factory,0x10000,0x100000,
 6 │ custom,0x40,0x00,0xf00000,0x100000,
   · ─────────────────┬─────────────────
   ·                  ╰── unknown variant `0x40`, expected `app` or `data`
   ╰────
  help: See the espressif documentation for information on the partition table format:
        
        https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html#creating-custom-tables

```
i.e. only the textual types "app" and "data" are currently supported. A similar error occurs when trying to provide a binary partition table.

I suppose for the time being I could use partition type "data" and subtype "undefined".

**Comment by jessebraham** [comment]
Good catch, as you can see we still don't have _complete_ support for partition tables. I will get this implemented soon and be sure to include it in our next release.
