### ISSUE TITLE
RFC: Relicense espflash under Apache-2.0 and MIT license

### ISSUE THREAD

**Issue by tom-borcin** [esp-rs/espflash#224]
Hello all,

firstly I want to emphesize that **this issue is an RFC**. Your comments are welcome.
I would like to open a discussion about the license we are using: GNU GENERAL PUBLIC LICENSE Version 2 (GPL-2.0).

### The problem

Espressif currently maintains 4 codebases for flashing of microcontrollers:

1. [Esptool](https://github.com/espressif/esptool) for flashing from OS
2. [esp-serial-flasher](https://github.com/espressif/esp-serial-flasher) for flashing from host microcontroller
3. [esptool-js](https://github.com/espressif/esptool-js) for flashing from web browser
4. [espflash](https://github.com/esp-rs/espflash) for flashing from OS

Maintaining 4 different codebases is difficult, costs a lot of resources, is prone to mistakes and defies DRY (Don't Repeat Yourself) principle. Our end goal is to have one common codebase that will be used by other three codebases. And we chose espflash as our common codebase.

Unfortunately, there is one problem that prevents us to use it as library whitin other projects: its [GPL-2.0 license](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html).

[esp-serial-flasher](https://github.com/espressif/esp-serial-flasher) and [esptool-js](https://github.com/espressif/esptool-js) are both licensed under Apache 2.0, which is incompatible with GPL-2.0 due to the restriction that terminates the grant of patent rights if the license sues over patent infringement. You can read about it in more detail [here](https://www.apache.org/licenses/GPL-compatibility.html).

Any library licensed under GPL-2.0 will enforce this licensing on any program that uses it. You can read about it [here](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#IfLibraryIsGPL). Because of this we would have to relicense [esp-serial-flasher](https://github.com/espressif/esp-serial-flasher) and [esptool-js](https://github.com/espressif/esptool-js) to GPL-2.0 as well as any SW that uses these codebases.

### Solution

From Espressif's and my perspective, the easiest and best solution to aforementioned problems would be relicensing of [espflash](https://github.com/esp-rs/espflash) to dual license it under MIT and Apache 2.0. Dual licensing under MIT and Apache 2.0 is widely accepted within Rust community and provides the most permissive licensing (MIT) that gives us patent grant (Apache 2.0) and as a whole is compatible with GPL-2.0.

### Open Discussion

On the other hand we may be wrong, so I want to spark a discussion. Let us know what you think about suggested solution and let us know if there are any other solutions you think should be considered. If you are a contributor and you agree with aforementioned solution to change current GPL-2.0 license to MIT and Apache 2.0, please state your consent in the comment.

CCing all espflash contributors: @icewind1991 @jessebraham @MabezDev @ryankurte @svenstaro @marcelbuesing @bugadani @JurajSadel @kelnos @tpambor @nim65s @bjoernQ @mertzt89 @pavlus @ducktec @ubergeek801 @alazartech @kyrias @maspetsberger @KerryRJ @zRedShift @SergioGasquez @sirhcel @mchodzikiewicz @hanhossain 

Tomas Borcin
Project Manager | Espressif Systems (Czech) s.r.o.
[www.espressif.com](http://www.espressif.com/)
Přízova 285/3, 602 00 Brno, Czech Republic

**Comment by MabezDev** [comment]
I agree with the motivation and consent to the relicensing.

**Comment by zRedShift** [comment]
Same, I consent as well.

**Comment by tpambor** [comment]
I am fine with relicensing.

**Comment by jessebraham** [comment]
I fully support this change!

**Comment by hanhossain** [comment]
I always wondered why it was GPL-2.0 anyway as most of the rust community is dual licensed MIT and Apache 2.0.

I consent to the relicensing.

**Comment by svenstaro** [comment]
I agree to the relicensing.

**Comment by mchodzikiewicz** [comment]
I also agree

śr., 31 sie 2022, 18:44 użytkownik Sven-Hendrik Haase <
***@***.***> napisał:

**Comment by mertzt89** [comment]
I'm in agreement

**Comment by bjoernQ** [comment]
I fully agree with relicensing `espflash`.

**Comment by SergioGasquez** [comment]
Agree!

**Comment by kyrias** [comment]
I consent to the relicensing.

**Comment by sirhcel** [comment]
I fully support relicensing. Thank you for bringing this up @tom-borcin!

**Comment by marcelbuesing** [comment]
I consent to the relicensing.

**Comment by alazartech** [comment]
I consent to the relicensing.

**Comment by kelnos** [comment]
I consent to relicensing to dual MIT/Apache-2.0.

**Comment by ducktec** [comment]
I consent to the proposed MIT/Apache-2.0 relicensing.

**Comment by KerryRJ** [comment]
I too agree with the relicensing.

**Comment by bugadani** [comment]
No objections from me

**Comment by icewind1991** [comment]
I agree with relicensing my contributions to MIT/Apache-2.0

**Comment by ubergeek801** [comment]
No argument here, and thanks for reaching out!

**Comment by JurajSadel** [comment]
I agree with the relicensing.

**Comment by pavlus** [comment]
No objections from my side.

**Comment by maspetsberger** [comment]
I agree with the relicensing.

**Comment by nim65s** [comment]
Agree

**Comment by zRedShift** [comment]
@tom-borcin looks like all the contributors have agreed (@ryankurte reacted with a thumbs up, the rest in a comment), so I believe there's a unanimous green light to go ahead with the re-licensing.

**Comment by jessebraham** [comment]
Thanks for the update @zRedShift! I believe Tomas has a couple days off, so either I or him will update this thread as soon as he's available.

Thank you everybody for playing nicely and agreeing to this! 😁 ❤️

**Comment by Janrupf** [comment]
I agree with the relicensing.

**Comment by jendakol** [comment]
I agree with the relicensing.

**Comment by ryankurte** [comment]
fine by me

**Comment by tom-borcin** [comment]
Thank you all for your comments. We have unanimous agreement to relicense espflash from GPL-2.0 to dual license of MIT and Apache-2.0. I will move on with relicensing.

**Comment by jessebraham** [comment]
Closed by #235
