### ISSUE TITLE
Add an option to verify the flash contents after flashing

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#259]
See:  
https://github.com/espressif/esptool/blob/590c2c68381b32e1d296d0b338b9d50a231169a5/esptool/cmds.py#L1135-L1173

**Comment by bugadani** [comment]
It would also be nice if we had the option to save a partition to a file. If verification requires reading back from flash, it probably shouldn't be very hard to add either function if the other exists :)

**Comment by SergioGasquez** [comment]
Related esptool docs: https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/serial-protocol.html#verifying-uploaded-data
