### ISSUE TITLE
v2.0.0.rc1 Doesn't support specifying baud-rate?

### ISSUE THREAD

**Issue by bsodmike** [esp-rs/espflash#289]
Previously this was possible, `espflash --monitor blinky --speed 920000` but now, it only allows a single command?

Please clarify, thanks!

**Comment by liebman** [comment]
The option changed to 
```
-b, --baud <BAUD>
```

**Comment by bsodmike** [comment]
Trying `-h` does not show any of the options though. Only the Command listing?

**Comment by jessebraham** [comment]
Flashing is now under a subcommand, and as mentioned `--speed` is now `--baud` (to be more in line with [esptool](https://github.com/espressif/esptool).

Running `espflash --help` will display the subcommands, running `espflash flash --help` will show the options for the `flash` subcommand. This is how [clap](https://docs.rs/clap/latest/clap/) works.

**Comment by bsodmike** [comment]
Thanks @jessebraham

**Comment by andywwright** [comment]
not being able to see all the options is very confusing at first and very inconvenient then. in this particular "feature" the new version to me is a regression, clap or not.
