### ISSUE TITLE
can't specify partition table in a workspace

### ISSUE THREAD

**Issue by liebman** [esp-rs/espflash#291]
In a cargo workspace like:

```
[workspace]
resolver = "2"
members = [
    "thing",
    "some-other-thing",
]
```

Where `thing` has 

```
[package.metadata.espflash]
partition_table = "partitions.csv"
```

The default partition table is used instead of the specified one. Looks like only the workspace  `Cargo.toml` is parsed leaving no place to declare a custom partition file. Ideally this should detect the workspace and load the `Cargo.toml` from the specific crate being processed.

**Comment by jessebraham** [comment]
Thanks for opening this issue, I'll fix this some time this week.
