### ISSUE TITLE
add defmt support

### ISSUE THREAD

**Issue by ImUrX** [esp-rs/espflash#316]
Adding a flag that parses defmt data would be nice for using with this tool, I currently just pipe the monitor to ``defmt-print``.
I think defmt could also be detected instead of adding a flag but idk which is preferred.

**Comment by jjdd12** [comment]
How is this supposed to work, I am new to using defmt, so I likely be understanding how exactly this works. When using defmt to log, do I have to add any parameters to the monitor command?

This is the output I get when I am expecting to some actual debug logs 
```

~~~~~   ~

```

**Comment by SergioGasquez** [comment]
See https://github.com/esp-rs/esp-println?tab=readme-ov-file#defmt for instructions, here is also a simple repo with defmt support: https://github.com/bugadani/esp32s3-defmt-example. We are working on updating the docs so we explain this process better (https://github.com/esp-rs/esp-println/pull/68) and we also add some documentation in espflash
