### ISSUE TITLE
Implement different reset strategies based on host OS and communication method

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#349]
This is a newer feature in `esptool`, see: https://github.com/espressif/esptool/blob/cc062082fb8ba0ca40cdd32e14fc673562b7b38f/esptool/reset.py

**Comment by jessebraham** [comment]
I had implemented this, but it doesn't actually seem to solve any problems. Given that additional code and bump in MSRV required, I'm not sure this is even worth implementing at this point.

**Comment by AVee** [comment]
This reset strategy seems to be added to EspTool to fix https://github.com/espressif/esptool/issues/712. It looks like it all about the timing of setting the RTS and DTR pins which appears to differ depending on the combination of OS, USB ports and USB-Serial converter chip. I'm getting the impression it is (mostly?) and issue with usb 3.x ports and/or usb-c serial converters, so it might well become more common over time.

I think I can come up with a fix which at least doesn't need the MSRV bump, and might end up being a bit more compact. I'll create a pull request once I've tested and cleaned it.

**Comment by AVee** [comment]
I created a pull request: https://github.com/esp-rs/espflash/pull/387

**Comment by SergioGasquez** [comment]
Can anyone affected by this issue check if #487 fixes the issue?
```
cargo install --git https://github.com/SergioGasquez/espflash --branch fix/resets cargo-espflash espflash
```
