### ISSUE TITLE
[ESP32C6] [USB_SERIAL_JTAG] [stub] Error while connecting to device

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/espflash#352]
Can't seem to connect to the ESP32C6 over USB serial jtag when using the stub, passing `--no-stub` it seems to work. Note that you'll have to change esp-println and co to use jtag-serial as output to see it working once flashed.

Maybe the stub just needs an update from upstream?

**Comment by jessebraham** [comment]
Yeah thanks I noticed this as well, forgot to open an issue. I think we just need to update the stub, but haven't confirmed.

**Comment by TYPEmber** [comment]
Same situation with ESP32C3 on M1 Mac
espflash's version is 2.1.0
