### ISSUE TITLE
espflash fails to enable terminal cursor when exited with ctrl-c

### ISSUE THREAD

**Issue by faern** [esp-rs/espflash#365]
If I terminate `espflash` while in the [port selection state](https://github.com/esp-rs/espflash/blob/90056f4691c7188194c3197e47b247c49aa72a54/espflash/src/cli/serial.rs#L179) my terminal cursor remains disabled. I guess this is because `espflash` uses terminal raw mode to disable the cursor, and then don't catch and handle the `SIGINT` signal and enables the cursor before exiting?

**Comment by jessebraham** [comment]
Sorry I just realized I closed this issue without saying anything 😅 I've added a fix for this issue which will be available in `2.0.0-rc.4`, which we're hoping to publish in the next week or two.

**Comment by faern** [comment]
Awesome! Thanks 😊 looking forward
