### ISSUE TITLE
Add note about permission issues on Linux

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/espflash#379]
Add a note on the readme about the usual error of  “Permission Denied” or “Port doesn’t exist”.  On most Linux distributions, the solution is to add the user to the `dialout` group (check e.g. `ls -l /dev/ttyUSB0 `to find the group) with a command like` sudo usermod -a -G dialout $USER`. You can call `su - $USER `to enable read and write permissions for the serial port without having to log out and back in again.

esptool does have such note: https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/basic-options.html#serial-port

**Comment by jneem** [comment]
probe-rs also has some udev-related [suggestions](https://probe.rs/docs/getting-started/probe-setup/) for setting up permissions. I'm not sure what the pros and cons of that are, compared with using the `dialout` group.
