### ISSUE TITLE
The ESP32-C2/H2 do not support 40MHz flash frequency, which is the default, resulting in poor UX

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#380]
Some potential solutions were suggested in #375:

> 1. Override in main (not so beautiful, but really simple)
> 2. Make default method, that accepts Chip (kinda duplicate functionality with Default trait, might be confusing)
> 3. Add flash frequency to  `Esp32Params` struct (IMHO this looks the best, but this is too complex for this PR, it might be that size should also be moved)

**Comment by SergioGasquez** [comment]
Same happens for ESP32-H2, 40MHz is not a supported flash frequency

**Comment by farbodpm** [comment]
May be I can help? Any body can guide me to do this enhancement ?

**Comment by SergioGasquez** [comment]
> May be I can help? Any body can guide me to do this enhancement ?

Hi! I started working on this late last Friday and forgot to assign it to me, sorry. I've just created #389 implementing the third suggested solution, feel free to have a look at it and suggest any feedback and, thanks for your help!
