### ISSUE TITLE
`cargo-espflash` installation fails on Windows 11

### ISSUE THREAD

**Issue by JurajSadel** [esp-rs/espflash#392]
`cargo install cargo-espflash espflash --force --git https://github.com/esp-rs/espflash.git`
results in
```rust
error: failed to run custom build command for `openssl-sys v0.9.87`

Caused by:
  process didn't exit successfully: `C:\Users\JurajSadel\espflash-forked\target\release\build\openssl-sys-8146bd689388a484\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\JurajSadel\\espflash-forked\\target\\release\\build\\openssl-sys-a6e27eef842a2ab1\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\JurajSadel\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.25.3+1.1.1t\src\lib.rs:504:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by SergioGasquez** [comment]
I was able to solve this error by installing [`perl` on Windows](https://strawberryperl.com/). We use [vendored openssl](https://github.com/esp-rs/espflash/blob/main/cargo-espflash/Cargo.toml#L24) which,[ according to the documentation](https://crates.io/crates/cargo).
> If using the vendored-openssl Cargo feature, then a static copy of OpenSSL will be built from source instead of using the system OpenSSL. This may require additional tools such as perl and make.
In theory, and again, according to documentation:
> On Windows, the system-provided Schannel will be used instead.

But not sure if in Windows 11 it is provided by default.

Not sure how we should fix this. Shall add `perl `as a requirement for Windows? It might be good to test on other Windows versions (?)

**Comment by SergioGasquez** [comment]
I did some more testing today with @JurajSadel, here is what we found:
- Removing the feature makes the installation fail in some Unix systems
  - It worked on my machines (Arch Linux)
  - Tried it on a Debian docker and failed
  
Did some test in Windows (without perl installed):
- For some reason, using those two combinations fails:
  - Latest version
    ```
    [target.'cfg(unix)'.dependencies]
    cargo = { version = "0.70.1", features = ["vendored-openssl"] }

    [target.'cfg(windows)'.dependencies]
    cargo = "0.70.1"
    ```
  - Current version
    ```
    [target.'cfg(unix)'.dependencies]
    cargo = { version = "0.70.1", features = ["vendored-openssl"] }
    
    [target.'cfg(windows)'.dependencies]
    cargo = "0.70.1"
    ```
      - In general, using the same cargo version results in failure
 - Some combinations of different versions seems to work, for example:
 ```
 [target.'cfg(unix)'.dependencies]
cargo = { version = "0.66.0", features = ["vendored-openssl"] }

[target.'cfg(windows)'.dependencies]
cargo = "0.70.1"
 ```

So far, the most "stable" solution that we found is installing `perl` on Windows, and leaving the feature there for all the targets.

**Comment by SergioGasquez** [comment]
As suggested by @georgik, using[ adding `resolver = "2"` to the workspace](https://github.com/esp-rs/espflash/compare/main...SergioGasquez:espflash:fix/windows-install#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) seems to fix the issue. With those changes, I've currently tested to install `cargo-espflash` from [`fix/windows-install` branch of my fork](https://github.com/esp-rs/espflash/compare/main...SergioGasquez:espflash:fix/windows-install) in the following scenarios successfully:
- MacOs
- Arch Linux
- Debian using Docker
- Windows 11
