### ISSUE TITLE
load_elf_to_flash() on esp32 hangs in FlashBegin command

### ISSUE THREAD

**Issue by asdfuser** [esp-rs/espflash#4]
esptool.py reports:
```
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
```

I never successfully flashed my ESP32 boards with `espflash /dev/ttyUSB0 image.elf`, it always reports a timeout:
```
$ ./target/debug/espflash /dev/ttyUSB0 --board-info
Chip type: Esp32
Flash size: Flash4MB
$ ./target/debug/espflash /dev/ttyUSB0 ../esp32-hal/target/xtensa-esp32-none-elf/release/examples/serial
Error: IO error while using serial port: Operation timed out
caused by: Operation timed out
```

There is simply no response to begin_command(Command::FlashBegin,..) in flasher.rs:418 and it times out in connection.rs:117 in command() while waiting for a response.

I compared the behaviour with esptool.py and I think the issue is:
* main() calls Flasher::connect() which calls start_connection to reset the chip and calls enable_flash()
* main is now able to communicate with the flash
* load_elf_to_flash() calls self.start_connection() which resets the chip and does not call enable_flash()
* SPI communication with the flash is not possible (on ESP32)

I solved this for my boards both by either removing start_connection() **or** adding enable_flash() in load_elf_to_flash(), but I don't know if that breaks anything on esp8266 (calling enable_flash() would result in two FlashBegin Commands being issued, one in enable_flash and then one in load_elf_to_flash())

**Comment by icewind1991** [comment]
Fixed with 28af942448fc56511c38bf35e97b3d2fde48031b
