### ISSUE TITLE
Cargo 0.72.0 was yanked from crates.io, breaking the patch that was just tagged as 2.0.1.

### ISSUE THREAD

**Issue by SpaceAceMonkey** [esp-rs/espflash#448]
This issue, https://github.com/esp-rs/espflash/pull/445, was used to patch cargo-espflash to require `cargo 0.72.0`. Version `0.72.0` of `cargo` has since been yanked, breaking builds of espflash/cargo-espflash in tag `v2.0.1.`

I was able to successfully execute `cargo install --path .` after reverting `0.72.0` to `0.71.0` in `cargo-espflash/Cargo.toml` and did not encounter the error that originally led to the patch being submitted.

**Comment by jessebraham** [comment]
You can still install using the `--locked` flag for the time being, as well.

**Comment by jessebraham** [comment]
A new version of `cargo`, 0.72.1, has been published.
