### ISSUE TITLE
Weird println! issue

### ISSUE THREAD

**Issue by manio** [esp-rs/espflash#457]
Hi,
During my work on the project i accidentally added polish national UTF-8 character to the debug message.
After some time I saw that once upon a time the text line is "mangled".

I was able to reproduce the problem like this:
`cargo generate https://github.com/esp-rs/esp-template`
Then I added the following code as the main loop:
```rust
    let mut delay = Delay::new(&clocks);
    loop {
        println!("Hello world! with UTF: wysyłam");
        delay.delay_ms(500u32);
    }
```
The above national character is:
`<ł> 322, Hex 0142, Oct 502, Digr l/`

Board: ESP32

And the result is:
![image](https://github.com/esp-rs/esp-hal/assets/583157/01caf88e-50d2-4522-8bb7-422825e2eacd)

Do you have any idea what is going on? :)

**Comment by bugadani** [comment]
I'll try and play with this today. The solution is probably a bit more nuanced than the suggestion above, as it needs to not die on mid-buffer errors as well.

**Comment by manio** [comment]
@bugadani Thanks, tested your change, and so far looking great (no more problems with UTF-8)
