### ISSUE TITLE
Attempt to read espflash config from project_dir/.config/espflash.toml

### ISSUE THREAD

**Issue by svenstaro** [esp-rs/espflash#469]
The config is currently only read system-wide (`$HOME/.config/espflash/espflash.toml`) but this is annoying if you work on multiple unrelated projects. I think cargo-espflash should first attempt to read `project_dir/.config/espflash.toml` and fall back to the system config if the former config doesn't exist.

**Comment by galah92** [comment]
Would also like a way to have a local config file (that take precedence over the global one). That would help multiple developers working on the same project were each has it's own serial mapping.
If there's another way to achieve that, I'll be happy to hear about it.
Also, our team mostly use the Cargo Runner (`.cargo/config.toml`), to run `espflash`, so ideally it would be a solution that supports this.
