### ISSUE TITLE
CLI argument structs are not marked `#[non_exhaustive]`

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#473]
This was an incredibly unfortunately oversight which was resulted in us needing to duplicate pretty much any new options between `cargo-espflash` and `espflash`. Fixing this is a semver-incompatible change so this will need to happen as part of the `v3` release, whenever that happens.

Perhaps another option would be to simply not provide semver guarantees for anything in the `cli` module (it is feature gated after all, and is only really useful for the binary application).
```[tasklist]
### Tasks
- [ ] `cli` module should warn that it does not provide semver guarantees
```

**Comment by SergioGasquez** [comment]
> Perhaps another option would be to simply not provide semver guarantees for anything in the cli module (it is feature gated after all, and is only really useful for the binary application).

As we discussed, we should probably go for this, hence it needs to be documented
