### ISSUE TITLE
Public API needs improvements to make it more extensible

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#474]
There are various public functions in the API, such as `load_elf_to_flash`, which are not extensible in their current form. These functions should be [marked as deprecated](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) and be replaced by functions which _are_ extensible. For instance, by taking a `#[non_exhaustive]` struct containing the required options.

Since we can deprecate the old functions this can be done in a semver-compatible way. We should identify additional functions which need improving and construct a task list below when able.

---

- [ ] `load_elf_to_flash_with_format`
- [ ] `load_elf_to_flash`

**Comment by SergioGasquez** [comment]
Since we are working towards `3.0` we don't need to deprecate functions, we can just remove them to simplify the codebase.
