### ISSUE TITLE
Identify chip reference

### ISSUE THREAD

**Issue by adrien3d** [esp-rs/espflash#491]
I am trying to get the reference (C6, S3 ....) of the chip I am using since it is embedded in a module.
Is it possible to have this information?
The best I got from `espflash board-info` is:
```
Chip type:         esp32 (revision v3.0)
Crystal frequency: 40MHz
Flash size:        4MB
Features:          WiFi, BT, Dual Core, 240MHz, Coding Scheme None
```

**Comment by bugadani** [comment]
Yours is an ESP32, no suffix. It's in the first line.

**Comment by SergioGasquez** [comment]
As @bugadani pointed, yours is an ESP32, thanks for the quick help @bugadani! I will be closing the issue, should you have any further question feel free to reopen it.
