### ISSUE TITLE
Allow specification of metadata depending on target

### ISSUE THREAD

**Issue by Natureshadow** [esp-rs/espflash#504]
For specifying a different partition table depending on the target (i.e. depending on a feature flag), it would be helpful to be able to define package metadata for espflash depending on a feature.

I don't know whether cargo allows that. If not, some other way to make partition tables, and other things that change depending on the target chip, configurable for these specific targets would also work.

**Comment by jessebraham** [comment]
Thanks for this issue! I am planning to do some related work next week so I will try to evaluate whether or not this is possible and get back to you with the results.
