### ISSUE TITLE
Serial port auto-detection

### ISSUE THREAD

**Issue by igrr** [esp-rs/espflash#52]
esptool.py implements serial port auto-detection logic, which lets users omit the port name in many cases. Similar logic could be implemented in this project.

Additionally, if the serial port is provided by a USB device and we can get enough information from the OS about the serial port to map it to a USB device, we can use VID:PID pairs to detect likely candidates for the development board serial ports. This should work pretty well e.g. for ESP32-C3 built-in USB_SERIAL_JTAG.

**Comment by icewind1991** [comment]
The main reason I'm hesitant with doing this is that sending reboot+sync command to random serial devices might have unforeseen consequences.

*If* we can be reasonably sure that a device is an esp device than this might be fine

**Comment by jessebraham** [comment]
I have begun working on this feature, should be pretty straight-forward.

One question I have is, how we should go about checking `VID`/`PID` values during the candidate serial port selection process?

I found the [espressif/usb-pids](https://github.com/espressif/usb-pids) repository which states that Espressif's `VID` is `0x303A` and lists a number of `PIDS`. I was thinking that for the auto-detection process we could only include these devices, which would somewhat address @icewind1991 's issue. Thoughts on this?

**Comment by jessebraham** [comment]
How do we want to go about verifying VID/PID values for this?

I did find the [espressif/usb-pids](https://github.com/espressif/usb-pids) repository which lists Espressif's VID and a number of PIDs, however this does not include all boards (eg. a number use the Silicon Labs CP2102).

**Comment by icewind1991** [comment]
I would generally err on the side of caution here, it's easy to tell the user to manually specify the port while trying to flash to a random device can cause larger issues.

My basic idea was:
- only try devices with from a known usb serial adapter
- only try to flash if there is a single matching device
  if there is more than one matching device, print out the options and tell the user to pick one manually

Adding a config option for adding additional VID/PID values would also be usefull
