### ISSUE TITLE
Support reading flash

### ISSUE THREAD

**Issue by t-moe** [esp-rs/espflash#539]
It would be nice if espflash could read back the flash into a file. 
Currently I have to rely on esptool.py to read back flash segments... Probe-rs is also not able to do this.

**Comment by t-moe** [comment]
Surprising! I didn't anticipate the implementation (requested by me) to happen so quickly. Big thanks @SergioGasquez ! Everything is functioning seamlessly. 🎉

**Comment by SergioGasquez** [comment]
> Surprising! I didn't anticipate the implementation (requested by me) to happen so quickly. Big thanks @SergioGasquez ! Everything is functioning seamlessly. 🎉
> 
> ((Yes, I still had to manually put the device into bootloader mode, because of [esp-rs/esp-flasher-stub#45](https://github.com/esp-rs/esp-flasher-stub/issues/45) ))

Thanks for the testing! I'll try to investigate the bootloader issue in the upcoming days
