### ISSUE TITLE
Feature request: provide functionality similar to `esptool.py elf2image`

### ISSUE THREAD

**Issue by ivmarkov** [esp-rs/espflash#57]
Subject says it all.

While having the flasher processing ELF files directly is gorgeous (and saves a ton of explanations to folks who are just starting with embedded development with the ESP), generating a `.BIN` file from an `.ELF` image does have one use case:
- OTA updates

**Comment by igrr** [comment]
Somewhat related to https://github.com/esp-rs/espflash/issues/53 — decoupling flashing from image generation will help support other imagine formats.

It's also useful for supporting flash encryption workflows later on.
