### ISSUE TITLE
Automatically select when both `cu` and `tty` is available

### ISSUE THREAD

**Issue by madsmtm** [esp-rs/espflash#608]
On macOS, when connecting my esp32c3, two devices `/dev/cu.usbmodem*` and `/dev/tty.usbmodem*` are created.

I'm not entirely sure what the difference between these are, but it seems like they both work for `espflash`' use-case. Would it make sense for `espflash` to automatically select one of them when both of them are available?

(Note that the exact device name differs based on which USB port I'm using, so I can't just define `ESPFLASH_PORT` and be done with it).

**Comment by SergioGasquez** [comment]
Not exactly sure what the difference is between `/dev/cu.usbmodem*` and `/dev/tty.usbmodem*` but it might not be worth to implement a feature in `espflash` that selects one over the other as there might be some differences. You can always use the [config file](https://github.com/esp-rs/espflash/tree/main/espflash#configuration-file) (locally or globally) to select the port or set the `ESPFLASH_PORT` environment variable.
