### ISSUE TITLE
Dependency `bytemuck v1.16.0` Yanked by Developer

### ISSUE THREAD

**Issue by josephrhobbs** [esp-rs/espflash#663]
On commit [2334907](https://github.com/esp-rs/espflash/commit/233490736646ca7bc29463a98df98d7ccf53439d) it seems that dependency `bytemuck-1.16.0` has been yanked from crates.io by its developer.  Will this cause problems in the future?

**Comment by SergioGasquez** [comment]
It shouldn't be an issue since there is a new patch release `1.16.3` but just created a PR updating the dep

**Comment by hobbsbros** [comment]
I understand!  Thank you!
