### ISSUE TITLE
me sale este error en mi codigo y no lo puedo solucionar, me podrian ayudar por favor 

### ISSUE THREAD

**Issue by Boo2904** [esp-rs/espflash#675]
esptool.py v4.6
Serial port COM8
Connecting.........
Chip is ESP32-D0WDQ6 (revision v1.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 0c:b8:15:c9:c7:4c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x0005afff...
Compressed 19744 bytes to 13604...
Writing at 0x00001000... (100 %)
Wrote 19744 bytes (13604 compressed) at 0x00001000 in 0.6 seconds (effective 270.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.1 seconds (effective 188.7 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.2 seconds (effective 326.9 kbit/s)...
Hash of data verified.
Compressed 303424 bytes to 171882...
Writing at 0x00010000... (9 %)
Writing at 0x0001be8a... (18 %)
Writing at 0x00024057... (27 %)
Writing at 0x000297c5... (36 %)
Writing at 0x0002eb6c... (45 %)
Writing at 0x00033f62... (54 %)
Writing at 0x00039424... (63 %)
Writing at 0x00041dc1... (72 %)
Writing at 0x0004c966... (81 %)
Writing at 0x00051e09... (90 %)
Writing at 0x00057428... (100 %)
Wrote 303424 bytes (171882 compressed) at 0x00010000 in 3.3 seconds (effective 729.7 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by SergioGasquez** [comment]
The error is related to [`esptool`](https://github.com/espressif/esptool), not `espflash`. Please report the issue in the proper repo and in English.
