### ISSUE TITLE
CHANGELOG says 3.1.1 was released 8/15/2023 but should read 9/15/2024

### ISSUE THREAD

**Issue by liebman** [esp-rs/espflash#683]
subject says it all

**Comment by SergioGasquez** [comment]
> [MabezDev](https://github.com/MabezDev) released this Aug 15

Version 3.1.1 was released 2024-08-15 as the changelog says, not sure if I'm missing something but I don't see the error.

**Comment by liebman** [comment]
You are correct - *sigh*
