### ISSUE TITLE
Add an option to prevent checking for new version

### ISSUE THREAD

**Issue by Thrathra** [esp-rs/espflash#688]
Hi, I'm working behind a proxy and it seems the programs tries to connect to crates.io in order to find updates.
As the requests times out, it takes a lot of time to even scan a board.
Is it possible to add an option to prevent such connections?

Thanks in advance!

**Comment by SergioGasquez** [comment]
Hi! Currently, we don't have any way of preventing this check, but we would happily accept a contribution adding an argument that skips calling https://github.com/esp-rs/espflash/blob/main/espflash/src/bin/espflash.rs#L167 (this should be also duplicated in cargo-espflash)

**Comment by Thrathra** [comment]
Thanks for your suggestion, I didn't see the right line at first. I opened a pull request.
