### ISSUE TITLE
Support flash encryption

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/espflash#70]
Flash encryption is supported by all chips from the **ESP32** and newer. We can encrypt data on the host and flash it to the target, assuming we first burn the encryption key into the target's eFuse.

For more details:  
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html

**Comment by jessebraham** [comment]
After some further discussion, it seems there's not really anything actionable here. I have written a short guide for using flash encryption in this gist:  
https://gist.github.com/jessebraham/0c7d86f9866614dc602e5d8e0e97c37a

If there is any specific functionality we need in the future we can open issues for that specifically.

**Comment by ostenning** [comment]
@jessebraham in your gist, you need to manually build a secure flash bootloader with esp-idf idf.py, and then manually pass that bootloader binary to espflash. 

That seems fairly incomplete to me. Shouldn't `espflash` be able to prepare the bootloader for encryption?
