### ISSUE TITLE
Test dir not part of crate

### ISSUE THREAD

**Issue by phodina** [esp-rs/espflash#73]
Hi,

I'm packaging this crate for [Guix System](https://guix.gnu.org/). Part of the build is also to run the test suite. As this crate is available on crates-io I just download it from there.

The only issue is when I execute the package build it fails on the tests as the test dir is not part of the crate tar.gz file. Could you please add the test directory to the crate manifest?

**Comment by jessebraham** [comment]
Sorry for the delay in responding to this issue.

I am not familiar with Guix, so I'm curious whether running the tests is a requirement of the package management system or if this is something you have decided to do? Just trying to understand the motivation behind this, as if it is the latter case then the obvious short-term solution would just be not to run these tests :)

I'm a little apprehensive of adding this directory mainly for two reasons:

1) the tests directory contains binaries, and will increase the size of the distribution artifact by a non-negligible amount
2) these tests do not actually cover all supported chips at present, so they are far from comprehensive; if we were to include this data I would like to see better coverage, personally

**Comment by phodina** [comment]
Hi @jessebraham,

Thanks for explaining the reasons. Well, Guix is little bit different GNU/Linux(or Hurd) distro, similar to Nix (and Nixos). They have novel way of packaging stuff to name the most important feature.

When porting a package you write a pkg description. Part of the that is the build system. For rust it's pretty obviously cargo. There are some additional changes not important here to get Rust code working on non FHS compliant distro.

> 2. these tests do not actually cover all supported chips at present, so they are far from comprehensive; if we were to include this data I would like to see better coverage, personally
However, the most important feature is that the build system attempts to run tests by default. Only if they pass will you build the package. IMHO the idea is verify the package is build and runs correctly if the author(s) already provide the test suite even though if it's incomplete - better to run some tests than none. 

This differs from other distros which usually in general just configure, build and install the package.

> 1. the tests directory contains binaries, and will increase the size of the distribution artifact by a non-negligible amount

Now I understand why Rust and also Python packages on pypi.org don't have any test directories packaged in their respective formats. That's why the tests always fail as the contents of the git repository is not the same as the content of the pypi or cargo package.

I do understand it's additional size and the need not to run test suits - probably applicable to many users. It's just nobody stressed this enough anywhere.

Then again it's not requirement as Guix can clone the whole repo instead of downloading the crate itself.

 So you can mark this ticket as solved :-)
