### ISSUE TITLE
Cannot connect to serial device

### ISSUE THREAD

**Issue by imxood** [esp-rs/espflash#85]
The serial device cannot be connected using espflash. However, the serial port can be opened by using espmonitor
![image](https://user-images.githubusercontent.com/14890680/139511919-cb021900-dc63-4cc8-9abc-5b16f3184154.png)

Just bought the esp32c3, ready to burn the program for the first time

Taobao link: https://item.taobao.com/item.htm?spm=a1z09.2.0.0.7eea2e8dJZTw4u&id=652515479052&_u=u1fh48sn6cb5

The compiled project is based on https://github.com/ivmarkov/rust-esp32-std-mini.git, simple modification

**Comment by pavlus** [comment]
May be related to #116

**Comment by jessebraham** [comment]
I'm going to close this due to inactivity. If you're able to test again using the newest version (`1.4.0`) and this problem persists, please feel free to re-open the issue.
