### ISSUE TITLE
Wait for board to enter flashing mode

### ISSUE THREAD

**Issue by hongquan** [esp-rs/espflash#90]
Some boards have hard buttons to manually switch to flashing mode. In that case, espmonitor often fails because it doesn't wait for human to press the button.

Please support this case.

**Comment by jessebraham** [comment]
Now that #92 has been merged `espflash` will make multiple connection attempts, so this should give you a chance to press the BOOT button.

If you feel this issue is still not resolved please feel free to re-open it explaining why!
